# Generated by Django 2.2 on 2019-07-23 15:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Background',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('date_posted', models.DateField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='backgrounds', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('hit_dice', models.IntegerField()),
                ('date_posted', models.DateField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Race',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('age', models.IntegerField()),
                ('alignment', models.CharField(max_length=100)),
                ('size', models.CharField(choices=[('T', 'Tiny'), ('S', 'Small'), ('M', 'Medium'), ('L', 'Large'), ('H', 'Huge'), ('G', 'Gargantuan')], default='M', max_length=1)),
                ('speed', models.IntegerField()),
                ('date_posted', models.DateField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='races', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RaceTrait',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('date_posted', models.DateField(auto_now=True)),
                ('race', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='traits', to='character_builder.Race')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Classtrait',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('date_posted', models.DateField(auto_now=True)),
                ('unlock_level', models.PositiveIntegerField(default=1)),
                ('test_num', models.PositiveIntegerField(default=1)),
                ('description', models.CharField(max_length=300)),
                ('Class', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='traits', to='character_builder.Class')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100)),
                ('level', models.PositiveIntegerField(default=1)),
                ('strength', models.IntegerField()),
                ('intelligence', models.IntegerField()),
                ('wisdom', models.IntegerField()),
                ('charisma', models.IntegerField()),
                ('constitution', models.IntegerField()),
                ('dextirity', models.IntegerField()),
                ('date_posted', models.DateField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='character', to=settings.AUTH_USER_MODEL)),
                ('background', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='character', to='character_builder.Background')),
                ('class_key', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='character', to='character_builder.Class')),
                ('race_key', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='character', to='character_builder.Race')),
            ],
        ),
        migrations.CreateModel(
            name='BackgroundTrait',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('date_posted', models.DateField(auto_now=True)),
                ('background', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='traits', to='character_builder.Background')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
