# Generated by Django 2.2 on 2019-07-23 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('character_builder', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classtrait',
            name='test_num',
        ),
    ]
