# Generated by Django 2.2 on 2019-07-23 16:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('character_builder', '0002_remove_classtrait_test_num'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classtrait',
            name='Class',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='features', to='character_builder.Class'),
        ),
    ]
