# Generated by Django 2.2 on 2019-06-10 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('character_builder', '0002_auto_20190606_1346'),
    ]

    operations = [
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('strength', models.IntegerField()),
                ('intelligence', models.IntegerField()),
                ('Wisdom', models.IntegerField()),
                ('Charisma', models.IntegerField()),
                ('Constitution', models.IntegerField()),
                ('Dextirity', models.IntegerField()),
            ],
        ),
        migrations.RenameField(
            model_name='race',
            old_name='Alighment',
            new_name='alignment',
        ),
        migrations.RenameField(
            model_name='race',
            old_name='Size',
            new_name='size',
        ),
        migrations.RenameField(
            model_name='race',
            old_name='Speed',
            new_name='speed',
        ),
    ]
