# Generated by Django 2.2 on 2019-06-10 17:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('character_builder', '0003_auto_20190610_1735'),
    ]

    operations = [
        migrations.RenameField(
            model_name='character',
            old_name='Charisma',
            new_name='charisma',
        ),
        migrations.RenameField(
            model_name='character',
            old_name='Constitution',
            new_name='constitution',
        ),
        migrations.RenameField(
            model_name='character',
            old_name='Dextirity',
            new_name='dextirity',
        ),
        migrations.RenameField(
            model_name='character',
            old_name='Wisdom',
            new_name='wisdom',
        ),
    ]
