# Generated by Django 2.2 on 2019-07-23 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('character_builder', '0004_saving_throw'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='saving_throw',
            name='description',
        ),
    ]
