# Generated by Django 2.2 on 2019-07-23 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('character_builder', '0005_remove_saving_throw_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classtrait',
            name='description',
            field=models.TextField(),
        ),
    ]
