# Generated by Django 2.2.1 on 2019-06-24 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('character_builder', '0009_auto_20190624_1600'),
    ]

    operations = [
        migrations.AlterField(
            model_name='race',
            name='size',
            field=models.CharField(choices=[('T', 'Tiny'), ('S', 'Small'), ('M', 'Medium'), ('L', 'Large'), ('H', 'Huge'), ('G', 'Gargantuan')], default='M', max_length=1),
        ),
    ]
