# Generated by Django 2.2 on 2019-06-25 15:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('character_builder', '0010_auto_20190624_1631'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='class_key',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='character_builder.Class'),
        ),
        migrations.AddField(
            model_name='character',
            name='level',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='classtrait',
            name='unlock_level',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
