# Generated by Django 2.2 on 2019-06-26 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('character_builder', '0011_auto_20190625_1546'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='character',
            name='class_key',
        ),
    ]
