# Generated by Django 2.2 on 2019-06-26 16:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('character_builder', '0013_character_class_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='race',
            name='trait',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='character_builder.Trait'),
            preserve_default=False,
        ),
    ]
