# Generated by Django 2.2 on 2019-06-26 16:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('character_builder', '0014_race_trait'),
    ]

    operations = [
        migrations.AlterField(
            model_name='race',
            name='trait',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='character_builder.Trait'),
        ),
    ]
