# Generated by Django 2.2 on 2019-06-26 16:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('character_builder', '0015_auto_20190626_1630'),
    ]

    operations = [
        migrations.AlterField(
            model_name='race',
            name='trait',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='character_builder.Trait'),
        ),
    ]
