# Generated by Django 2.2 on 2019-06-26 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('character_builder', '0016_auto_20190626_1634'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='race',
            name='trait',
        ),
        migrations.AddField(
            model_name='race',
            name='trait',
            field=models.ManyToManyField(to='character_builder.Trait'),
        ),
    ]
