# Generated by Django 2.2 on 2019-06-26 20:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('character_builder', '0017_auto_20190626_1703'),
    ]

    operations = [
        migrations.RenameField(
            model_name='race',
            old_name='trait',
            new_name='traits',
        ),
    ]
