# Generated by Django 2.2 on 2019-07-01 16:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('character_builder', '0020_remove_trait_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='race',
            name='traits',
        ),
        migrations.AddField(
            model_name='racetrait',
            name='race',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='character_builder.Race'),
            preserve_default=False,
        ),
    ]
