# Generated by Django 2.2 on 2019-07-09 18:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('character_builder', '0021_auto_20190701_1610'),
    ]

    operations = [
        migrations.AlterField(
            model_name='racetrait',
            name='race',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='traits', to='character_builder.Race'),
        ),
    ]
