# Generated by Django 2.2 on 2019-07-10 19:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('character_builder', '0022_auto_20190709_1852'),
    ]

    operations = [
        migrations.AlterField(
            model_name='background',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='background_owner', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='character',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='character_owner', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='class',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='class_owner', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='race',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='race_owner', to=settings.AUTH_USER_MODEL),
        ),
    ]
