# Generated by Django 2.2 on 2019-07-10 20:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('character_builder', '0025_auto_20190710_2019'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='background',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='backgrounds', to='character_builder.Background'),
        ),
        migrations.AlterField(
            model_name='character',
            name='class_key',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='classes', to='character_builder.Class'),
        ),
        migrations.AlterField(
            model_name='character',
            name='race_key',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='races', to='character_builder.Race'),
        ),
    ]
