# Generated by Django 2.2 on 2019-07-10 21:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('character_builder', '0026_auto_20190710_2028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='character', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='character',
            name='background',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='character', to='character_builder.Background'),
        ),
        migrations.AlterField(
            model_name='character',
            name='class_key',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='character', to='character_builder.Class'),
        ),
        migrations.AlterField(
            model_name='character',
            name='race_key',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='character', to='character_builder.Race'),
        ),
        migrations.CreateModel(
            name='BackgroundTrait',
            fields=[
                ('trait_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='character_builder.Trait')),
                ('background', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='traits', to='character_builder.Background')),
            ],
            bases=('character_builder.trait',),
        ),
    ]
