# Generated by Django 2.2 on 2019-07-19 15:11

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('character_builder', '0027_auto_20190710_2124'),
    ]

    operations = [
        migrations.AddField(
            model_name='race',
            name='date_created',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
