# Generated by Django 2.2 on 2019-07-19 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('character_builder', '0028_race_date_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='race',
            name='date_created',
            field=models.DateField(auto_now_add=True),
        ),
    ]
