# Generated by Django 2.2 on 2019-07-19 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('character_builder', '0030_auto_20190719_1522'),
    ]

    operations = [
        migrations.AddField(
            model_name='background',
            name='date_created',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='character',
            name='date_created',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='class',
            name='date_created',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='trait',
            name='date_created',
            field=models.DateField(auto_now=True),
        ),
    ]
